config/routes.rb
Rails.application.routes.draw do
  root             "static_pages#home"
  mount Commontator::Engine => '/commontator'
  mount Soulmate::Server, :at => "/autocomplete"

  get "help"    => "static_pages#help"
  get "about"   => "static_pages#about"
  get "contact" => "static_pages#contact"

  devise_for :users
  devise_scope :user do
    get "sign_out", to: "devise/sessions#destroy"
    get "sign_in", to: "devise/sessions#new"
    get "sign_up", to: "devise/registrations#new"
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :statuses do
    member do
      put "like", to: "statuses#like"
      put "unlike", to: "statuses#unlike"
    end
  end

  resources :tasks do
    member do
      put "like", to: "tasks#like"
      put "unlike", to: "tasks#unlike"
    end
  end

  resources :comments
  resources :activities

  resources :relationships, only: [:create, :destroy] do
    member do
        put "follow", to: "relationships#follow"
        put "unfollow", to: "relationships#unfollow"
    end
  end

  resources :conversations do
    resources :messages
  end

  resources :groups do
    resource :user_groups
    get "add_members" => "user_groups#show"
  end

  resources :events do
    resource :user_events
    get "add_members" => "user_events#show"
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :correct_user, only: :destroy
  respond_to :html, :json

  def show
    @status = Status.find params[:id]
    @status.comments.build
    @user = current_user
    @user_list = current_user.following
  end

  def create
    @status = current_user.statuses.build status_params
    if @status.save
      flash[:success] = "Status created!"
      redirect_to root_url
    else
      @feed_items = []
      render "static_pages/home"
    end
  end

  def update
    @status = Status.find params[:id]
    @status.update_attributes status_params
    respond_with @status
  end

  def destroy
    @status.destroy
    flash[:success] = "Status deleted"
    redirect_to request.referrer || root_url
  end

  def like
    @status = Status.find params[:id]
    @status.liked_by current_user
    @status.create_activity key: "status.like"
    if request.xhr?
      render json: {count: @status.get_likes.size, id: params[:id]}
    else
      redirect_to @status
    end
  end

  def unlike
    @status= Status.find params[:id]
    @status.unliked_by current_user
    @status.create_activity key: "status.unlike"
    if request.xhr?
      render json: {count: @status.get_likes.size, id: params[:id]}
    else
      redirect_to @status
    end
  end

  private
  def status_params
    params.require(:status).permit :content, :picture
  end

  def correct_user
    @status = current_user.statuses.find_by id: params[:id]
    redirect_to root_url if @status.nil?
  end
end

app/views/statuses/_status.html.erb
<li id="<%= status.id %>">
  <span class="avatar">
    <%= image_tag(status.user.avatar.url(:status)) %>
  </span>
  <span class="user">
    <%= link_to status.user.name, status.user %>
  </span>
  <br>
  <span class="timestamp text-success">
    <%= link_to "Posted #{time_ago_in_words(status.created_at)} ago.", status %>
    <% if current_user? status.user %>
      <%= link_to "", status, method: :delete, data: {confirm: "You sure?"}, class: "glyphicon glyphicon-remove text-danger" %>
    <% end %>
  </span></br></br>
  <span class="content">
    <%= best_in_place_if current_user?(status.user), status, :content, :ok_button => "ok", :ok_button_class => "btn btn-success ", :cancel_button => "X", :cancel_button_class => "btn btn-danger" %></br>
    <%= image_tag status.picture.url if status.picture? %>
  </span></br>
  <span>
    <% if current_user.liked? status %>
      <%= link_to "Unlike", unlike_status_path(status), class: 'vote', method: :put, remote: true, data: { toggle_text: 'Like', toggle_href: like_status_path(status), id: status.id } %>
    <% else %>
      <%= link_to "Like", like_status_path(status), class: 'vote', method: :put, remote: true, data: { toggle_text: 'Unlike', toggle_href: unlike_status_path(status), id: status.id } %>
    <% end %>
  </span>
  <span class="votes-count" data-id="<%= status.id %>">
    <%= status.get_likes.size %>
  </span>
  Likes</br></br>
  Comments:</br>
  <% @comments = status.comments %>
  <span id="status-comment<%= status.id %>">
    <%= render @comments %>
  </span>
  <span id="form-status">
    <%= form_for Comment.new , remote: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
        <div class="field">
          <%= f.hidden_field :status_id, value: status.id %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.text_area :content, placeholder: "Compose new comment...", class: "form-control" %>
          <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
        </div>
      <%= f.submit "Comment", class: "btn btn-primary" %>
    <% end %>
  </span>
</li>
</br>

<script>
  data = <%= raw User.pluck(:name).compact.to_json %>;
  $('textarea').atwho({at:"@", 'data':data});
</script>

app/views/statuses/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-3">
    <section class="user_info">
      <h1>
        <%= image_tag(@user.avatar.url(:medium)) %>
        <%= @user.name %></br></br>
        <% if @user.online? %>
          <span class="glyphicon glyphicon-user text-success"></span>
          Online
        <% else %>
          <span class="glyphicon glyphicon-user"></span>
          Offline
        <% end %>
      </h1>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
    <section class="group">
      <%= render 'shared/group' %>
    </section>
  </aside>
  <aside class="col-md-7">
      <ol class="statuses">
        <%= render @status %>
      </ol>
  </aside>
  <aside class="col-md-2">
    <%= render 'shared/friend_online' %>
  </aside>
</div>
<%= subscribe_to "/comments/new" %>