config/routes.rb
Rails.application.routes.draw do
  root             "static_pages#home"
  mount Commontator::Engine => '/commontator'
  mount Soulmate::Server, :at => "/autocomplete"

  get "help"    => "static_pages#help"
  get "about"   => "static_pages#about"
  get "contact" => "static_pages#contact"

  devise_for :users
  devise_scope :user do
    get "sign_out", to: "devise/sessions#destroy"
    get "sign_in", to: "devise/sessions#new"
    get "sign_up", to: "devise/registrations#new"
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :statuses do
    member do
      put "like", to: "statuses#like"
      put "unlike", to: "statuses#unlike"
    end
  end

  resources :tasks do
    member do
      put "like", to: "tasks#like"
      put "unlike", to: "tasks#unlike"
    end
  end

  resources :comments
  resources :activities

  resources :relationships, only: [:create, :destroy] do
    member do
        put "follow", to: "relationships#follow"
        put "unfollow", to: "relationships#unfollow"
    end
  end

  resources :conversations do
    resources :messages
  end

  resources :groups do
    resource :user_groups
    get "add_members" => "user_groups#show"
  end

  resources :events do
    resource :user_events
    get "add_members" => "user_events#show"
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :users, through: :user_events
  has_many :user_events, dependent: :destroy
  has_many :statuses, dependent: :destroy
  belongs_to :admin, class_name: "User"

  accepts_nested_attributes_for :user_events, allow_destroy: :true
  accepts_nested_attributes_for :statuses, allow_destroy: :true

  class << self
    def remove_old_event
      where("time_end < ?", DateTime.now).destroy_all
    end
  end
end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  def show
    @group = Group.find params[:group_id]
  end
end

app/views/user_groups/show.html.erb
<% provide :title, "Add member" %>
<h1>Add member</h1>
<h3><%= link_to @group.name, @group %></h3>
<%= form_for @group do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="row">
    <table class="table">
      <%= f.collection_check_boxes :user_ids, User.all, :id, :name do |b| %>
        <tr>
          <%= b.label do %>
            <th><%= b.text %></th>
            <th class="selection_checkbox"><%= b.check_box %></th>
          <% end %>
        </tr>
      <% end %>
    </table>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>