config/routes.rb
Rails.application.routes.draw do
  root             "static_pages#home"
  mount Commontator::Engine => '/commontator'
  mount Soulmate::Server, :at => "/autocomplete"

  get "help"    => "static_pages#help"
  get "about"   => "static_pages#about"
  get "contact" => "static_pages#contact"

  devise_for :users
  devise_scope :user do
    get "sign_out", to: "devise/sessions#destroy"
    get "sign_in", to: "devise/sessions#new"
    get "sign_up", to: "devise/registrations#new"
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :statuses do
    member do
      put "like", to: "statuses#like"
      put "unlike", to: "statuses#unlike"
    end
  end

  resources :tasks do
    member do
      put "like", to: "tasks#like"
      put "unlike", to: "tasks#unlike"
    end
  end

  resources :comments
  resources :activities

  resources :relationships, only: [:create, :destroy] do
    member do
        put "follow", to: "relationships#follow"
        put "unfollow", to: "relationships#unfollow"
    end
  end

  resources :conversations do
    resources :messages
  end

  resources :groups do
    resource :user_groups
    get "add_members" => "user_groups#show"
  end

  resources :events do
    resource :user_events
    get "add_members" => "user_events#show"
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  after_save :load_into_soulmate
  before_destroy :remove_from_soulmate

  has_many :users, through: :user_groups
  has_many :user_groups, dependent: :destroy
  has_many :statuses, dependent: :destroy
  has_many :tasks, dependent: :destroy
  belongs_to :admin, class_name: "User"

  accepts_nested_attributes_for :user_groups, allow_destroy: :true
  accepts_nested_attributes_for :statuses, allow_destroy: :true
  accepts_nested_attributes_for :tasks, allow_destroy: :true

  def self.search search
    if search
      Group.where("name LIKE ?", "%#{search}%")
    else
      Group.all
    end
  end

  private

  def load_into_soulmate
    loader = Soulmate::Loader.new("groups")
    loader.add("term" => name, "id" => self.id, "data" => {
      "link" => Rails.application.routes.url_helpers.group_path(self)
      })
  end

  def remove_from_soulmate
    loader = Soulmate::Loader.new("groups")
    loader.remove("id" => self.id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def show
    @admin = @group.admin
    @group.statuses.build
    @group.tasks.build
    @statuses = []
    @tasks = []
    @group.users.each do|user|
      user.statuses.status_in_group(@group.id).each do |status|
        @statuses << status
      end
      user.tasks.task_in_group(@group.id).each do |task|
        @tasks << task
      end
    end
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new group_params
    @group.user_ids << current_user.id
    if @group.save
      UserGroup.create user_id: current_user.id, group_id: @group.id
      flash[:success] = "Group create success"
      redirect_to @group
    else
      flash[:danger] = "Create failed"
      render :new
    end
  end

  def update
    unless params[:confirm]
      if @group.update_attributes group_params
        flash[:success] = "Edited success"
        redirect_to @group
      else
        flash[:danger] = "Edit failed"
        render :edit
      end
    else
      @group.user_groups.find_by_user_id(current_user.id).destroy
      flash[:success] = "Leave group successfully"
      redirect_to root_path
    end
  end

  def destroy
    @group.destroy
    flash[:success] = "Deleted success"
    redirect_to root_path
  end

  private
  def group_params
    params.require(:group).permit :name, :description, :admin_id, user_ids: [],
      user_groups_attributes: [:id, :user_id, :group_id],
      statuses_attributes: [:id, :group_id, :user_id, :content, :picture],
      tasks_attributes: [:id, :group_id, :user_id, :name, :content, :deadline]
  end

  def set_group
    @group = Group.find params[:id]
  end
end

app/views/groups/_user.html.erb
<tr>
  <td><%= user.name %></td>
  <td><%= user.id == @group.admin_id ? "Admin" : "Member" %></td>
</tr>

app/views/groups/edit.html.erb
<%= form_for @group do |f| %>
  <div class="field">
    <%= f.label :groupname %><br/>
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :description %><br/>
    <%= f.text_field :description, autofocus: true %>
  </div>

  <div class="field">
    <%= f.hidden_field :admin_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/groups/new.html.erb
<%= form_for @group do |f| %>
  <div class="field">
    <%= f.label :groupname %><br/>
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :description %><br/>
    <%= f.text_field :description, autofocus: true %>
  </div>

  <div class="field">
    <%= f.hidden_field :admin_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/groups/show.html.erb
<% provide :title, @group.name %>
<div class="row">
  <aside class="col-md-2">
    <section>
      <h1>
        Group:
        <%= @group.name %>
      </h1>
      <h4>
        Admin name:
        <%= @admin.name %><br/>
        Description:
        <%= @group.description %><br/>
      </h4>
    </section>
    <section>
      <% if current_user == @admin %>
        <%= link_to "Add Members", group_add_members_path(@group), class:"btn btn-success btn-sm" %>
        <%= link_to "Edit Group", edit_group_path(@group), class:"btn btn-primary btn-sm" %>
        <%= link_to "Delete Group", group_path(@group), method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-danger btn-sm" %>
      <% else %>
        <%= link_to "Leave this group", edit_group_path(@group, confirm: true), class:"btn btn-danger btn-sm" %>
      <% end %>
    </section>
    <section class="group_info">
      <table class="table">
        <thead>
          <tr>
            <th>User name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <%= render partial: "user", collection: @group.users %>
        </tbody>
      </table>
    </section>
  </aside>
  <aside class="col-md-5">
    <h3>Statuses Feed</h3>
      <section class="micropost_form">
        <%= form_for @group, html: {multipart: true} do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <%= f.fields_for :statuses do |p| %>
            <% if p.object.try(:content).present? %>
              <% p.hidden_field :user_id, value: p.object.user_id %>
              <% p.hidden_field :content, value: p.object.content %>
              <% p.hidden_field :picture, value: p.object.picture %>
            <% else%>
              <div class="field">
                <%= p.hidden_field :user_id, value: current_user.id %>
                <%= p.text_area :content, placeholder: "Compose new status...", class: "form-control" %>
                <span class="picture">
                  <%= p.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
                </span>
              </div>
            <% end %>
          <% end %>
          <%= f.submit "Post", class: "btn btn-primary" %>
        <% end %>
      </section>
      <ol class="sttuses">
        <% @statuses.each do |status| %>
          <%= render 'statuses/status', status: status %>
        <% end %>
      </ol>
  </aside>
  <aside class="col-md-5">
    <h3>Tasks</h3>
    <section class="micropost_form">
      <%= form_for @group, html: {multipart: true} do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <%= f.fields_for :tasks do |p| %>
          <% if p.object.try(:content).present? %>
            <% p.hidden_field :name, value: p.object.name %>
            <% p.hidden_field :user_id, value: p.object.user_id %>
            <% p.hidden_field :content, value: p.object.content %>
            <% p.hidden_field :deadline, value: p.object.deadline %>
          <% else%>
            <div class="field">
              <%= p.label :name %>
              <%= p.text_field :name, placeholder: "Compose new task name...", class: "form-control" %>
            </div>
            <div class="field">
              <%= p.label :content %>
              <%= p.text_area :content, placeholder: "Compose new task content...", class: "form-control" %>
            </div>
            <div class="field">
              <%= p.label :Assignee %>
              <%= p.select :user_id, options_from_collection_for_select(User.all, "id", "name") %>
            </div>
            <div class="field">
              <%= p.label :deadline %>
              <%= p.date_field :deadline %>
            </div>
          <% end %>
        <% end %>
        <%= f.submit "Create", class: "btn btn-primary" %>
      <% end %>
    </section>
    <ol class="tasks">
      <% @tasks.each do |task| %>
        <%= render 'tasks/task', task: task %>
      <% end %>
    </ol>
  </aside>
</div>

<%= subscribe_to "/comments/new" %>

<script type="text/javascript">
  $('#status_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>