config/routes.rb
Rails.application.routes.draw do
  root             "static_pages#home"
  mount Commontator::Engine => '/commontator'
  mount Soulmate::Server, :at => "/autocomplete"

  get "help"    => "static_pages#help"
  get "about"   => "static_pages#about"
  get "contact" => "static_pages#contact"

  devise_for :users
  devise_scope :user do
    get "sign_out", to: "devise/sessions#destroy"
    get "sign_in", to: "devise/sessions#new"
    get "sign_up", to: "devise/registrations#new"
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :statuses do
    member do
      put "like", to: "statuses#like"
      put "unlike", to: "statuses#unlike"
    end
  end

  resources :tasks do
    member do
      put "like", to: "tasks#like"
      put "unlike", to: "tasks#unlike"
    end
  end

  resources :comments
  resources :activities

  resources :relationships, only: [:create, :destroy] do
    member do
        put "follow", to: "relationships#follow"
        put "unfollow", to: "relationships#unfollow"
    end
  end

  resources :conversations do
    resources :messages
  end

  resources :groups do
    resource :user_groups
    get "add_members" => "user_groups#show"
  end

  resources :events do
    resource :user_events
    get "add_members" => "user_events#show"
  end
end

app/views/shared/_activity.html.erb
<div class="col-sm-12">
<ul class="list-group">
  <% @activities.each do |activity| %>
    <li style="list-style: none;">
      <% if activity.owner %>
        <strong>
          <%= image_tag(activity.owner.avatar.url(:comment)) %>
          <%= activity.owner.name %>
        </strong>
      <% else %>
        <strong>Guest%></strong>
      <% end %>
      <%= render_activity activity, display: :i18n %>
      <% if activity.trackable %>
        <% if activity.trackable_type == "Status" %>
          "<%= link_to activity.trackable.name, status_path(activity.trackable) %>"
        <% elsif activity.trackable_type == "Comment" %>
          "<%= activity.trackable.name %>"
          in status
          "<%= link_to activity.trackable.status.name, status_path(activity.trackable.status) %>"
        <% end %>
      <% else %>
        with unknown title.
      <% end %>
      </br>
      <span class="glyphicon glyphicon-<%= activity.key.match(/\.(.*)/)[1] %>">
        <small class="text-muted"><%= time_ago_in_words(activity.created_at) %> ago.</small>
      </span>
    </li>
    <hr>
  <% end %>
  </ul>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_event.html.erb
<h3>Event</h3>
<%= link_to "Create New Event", new_event_path, class: "btn btn-success" %></br>
<% unless current_user.events.count == 0 %>
  <h4>Events list:</h4>
  <% current_user.events.each do |event| %>
    <li><%= link_to event.name, event %></li>
  <% end %>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="sttuses">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_events.html.erb
<h4>Feeds:</h4>
<% if @feed_events.any? %>
  <ol class="sttuses">
    <%= render @feed_events %>
  </ol>
<% end %>

app/views/shared/_friend_online.html.erb
<h2>Friend Online</h2>
<% @user_list.each do |user| %>
  <% if user.online? && (current_user?(user) != true) %>
    <%= image_tag user.avatar.url(:comment) %>
    <%= link_to user.name, "#", class: "start-conversation", "data-sid" => current_user.id, "data-rid" => user.id %>
    <span class="glyphicon glyphicon-user text-success pull-right" style="margin-top: 5px;"></span>
  <% end %>
<% end %>

app/views/shared/_group.html.erb
<h3>Group Manager</h3>
<%= link_to "Create New Group", new_group_path, class: "btn btn-success" %></br>
<% unless current_user.groups.count == 0 %>
  <h4>Groups list:</h4>
  <% current_user.groups.each do |group| %>
    <li><%= link_to group.name, group %></li>
  <% end %>
<% end %>

app/views/shared/_search.html.erb
<div>
  <h2>Search Users and Groups</h2>
  <%= form_tag users_path, method: :get do %>
    <%= text_field_tag "search", params[:search], placeholder: "Search", autocomplete: :off %>
    <%= submit_tag "Search" %>
  <% end %>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong class="follows-count" data-id="<%= @user.id %>">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_status_form.html.erb
<%= form_for @status, html: {multipart: true} do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new status...", class: "form-control" %>
    <span class="picture">
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    </span>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

<script type="text/javascript">
  $('#status_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_user_info.html.erb
<h1>
  <%= image_tag current_user.avatar.url(:medium) %>
  </br><%= best_in_place current_user, :name, :ok_button => "ok", :ok_button_class => "btn btn-success ", :cancel_button => "X", :cancel_button_class => "btn btn-danger" %>
</h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.statuses.status_not_group_and_event.count, "status") %></span>